### ISSUE TITLE
It would be nice if the backup file opened easily on Android

### ISSUE THREAD

**Issue by evilteach** [Ranakastrasz/JanCor#1]
The latest version is a big improvement.
I opened the app, and closed it without entering any data.

The backup directory was created.
The file has a backup extension.
I would prefer if it were left as a .txt extension so that the editor on my android would be able to open it with just a click.

**Comment by Ranakastrasz** [comment]
It is a .txt extension on my computer, so there is something weird going on.

**Comment by evilteach** [comment]
Ok.  i see that the files are txt files.
it's a mistake on my part.
