### ISSUE TITLE
Backup: not quite what I had envisioned.

### ISSUE THREAD

**Issue by evilteach** [Ranakastrasz/JanCor#2]
As today is 12/09/2020, I had expected to see under the backup folder, another folder.
That folder would be named 2020-12-09.
Under that folder would be the backup file.

**Comment by Ranakastrasz** [comment]
I do not understand. Why do you want a backup folder, with subfolders, each of which contain a single file?

**Comment by evilteach** [comment]
Ya. this is fine too.
